### ISSUE TITLE
Question about behavior of WJEObject()/WJEObjectF()

### ISSUE THREAD

**Issue by coreystinson** [netmail-open/wjelement#100]
I've gotten into some trouble and I have to admit I'm baffled.  I'm trying to iterate over an array of objects.  My approach is a loop as follows:

m_in = WJEObjectF(doc_in, WJE_GET, NULL, "manifests[%u]", manifest);

In the loop, I increment 'manifest' counter until I index past the end of the array at which point I assume I'll get a NULL return.  I know this works in another application that I have, but that application is using an older build of the library (probably a year old).

However, using a contemporary build of the library instead of receiving a NULL value when indexing past the end of the array I get a new, empty object.  WJEObject() seems to act the same.

I have that sneaking feeling that my other application is going to break as well as soon as I upgrade the underlying wjelement build.

Have I lost my mind and overlooked something obvious? :)  If this is a behavior change, was it intentional - and if so, what is the current suggested method for iterating over the contents of an existing array?

**Comment by minego** [comment]
When passing WJE_GET you should never get a new object. If you are then the
library is misbehaving. That option should not modify the document.

I'd that is the current behavior then perhaps something broke recently.

**Comment by coreystinson** [comment]
Thanks for the feedback.  Given your thoughts, I figured I really had to be doing something wrong.  I went back and examined it figured out that I was inserting something back into the document erroneously (my input document, rather than the output document I was generating some results to) which explained the behavior.  Sorry for the false alarm!

**Comment by minego** [comment]
Ah! I'm glad to hear that. Thanks.
