### ISSUE TITLE
How to get an attribute whose key includes parenthesis?

### ISSUE THREAD

**Issue by vfiorin** [netmail-open/wjelement#107]
Hi,
I'm trying to retrieve an attribute whose key includes parenthesis: I'm able to get the element with `WJEChild`, however I get NULL when using `WJEGet`. Is there any way to get the element by the outermost container?

For example, given the JSON:
```json
{ "key(0)" : 0
}
```

```c
WJElement element; // root of previous JSON

WJElement child = NULL;
child = WJEGet(element, "key(0)", NULL); // child is null
child = WJEChild(element, "key(0)", WJE_GET); // child is the item with value 0
```

Thanks

**Comment by vfiorin** [comment]
BTW, it seems that also the creation APIs fail when adding an attribute whose key includes parenthesis.

More specifically, in the snippet below, the `WJEString` will fail to add the attribute, and the object will be empty:

```c
WJElement doc = WJEObject(NULL, NULL, WJE_NEW);
WJEString(doc, "key(0)", WJE_SET, "abc");
```

**Comment by penduin** [comment]
The short answer is that you want WJEChild:

WJEString(WJEChild(doc, "key(0)", WJE_NEW), NULL, WJE_SET, "abc");
char *str = WJEString(WJEChild(doc, "key(0)", WJE_GET), NULL, WJE_GET, NULL);

No selector syntax is used with WJEChild, so the string you pass in
will be the literal attribute name.  That also means you need a direct
handle to its parent (doc, in our example).

**Comment by vfiorin** [comment]
Thanks for the quick reply.

I followed your suggestion and change the sample to use the direct handle to the parent: it worked!

Thanks again.
