### ISSUE TITLE
Why is '\v' (vertical tab) escaped by WJWriteString?

### ISSUE THREAD

**Issue by NikoDelarich** [netmail-open/wjelement#110]
Hi,

WJWriteString() encodes all special characters (except forward solidus) specified on [json.org](https://www.json.org/img/string.png) and additionally `\v` (vertical tab, 0xB):
https://github.com/netmail-open/wjelement/blob/51fe5f2a724df956e602fa39c6d3b342c7333fb9/src/wjwriter/wjwriter.c#L456-L464

E.g. encoding "12\\v34" will result in "12\\\\v34" which is not recognized as valid JSON by Chrome: 

> \> JSON.parse('"\\\\v"');
> Uncaught SyntaxError: Bad escaped character in JSON at position 2

Why this character is encoded? Wouldn't it be better to print `\u000b` instead?

**Comment by penduin** [comment]
We can't remember any reason we'd be treating vertical tabs that way.  I don't see a problem with removing that case, or with using the unicode you suggested.  If you make some modifications that satisfy your use case, please send a pull request!

**Comment by NikoDelarich** [comment]
Thanks for merging!
