### ISSUE TITLE
Memleak while validating array elements

### ISSUE THREAD

**Issue by moresascha** [netmail-open/wjelement#39]
It seems that there is a leak in schema.c while processing array elements. You are allocating memory in line 739 (MemAsprintf) without freeing it. I added MemFree(str); at the end of the while-loop and that fixed it for me (tested with valgrind).

or am I missing something completely?

Greetings

**Comment by penduin** [comment]
good catch!  I'll double-check and patch that up tomorrow.  Thank you!
-Owen



-- Sent from my HP TouchPadOn Feb 10, 2015 5:55 PM, moresascha <notifications@github.com> wrote: 

It seems that there is a leak in schema.c while processing array elements. You are allocating memory in line 739 (MemAsprintf) without freeing it. I added MemFree(str); at the end of the while-loop and that fixed it for me (tested with valgrind).


or am I missing something completely?


Greetings

**Comment by penduin** [comment]
committed a fix.  (using MemRelease, but the same in spirit as your change)  thanks again!
