### ISSUE TITLE
No uninstall option in generated makefile

### ISSUE THREAD

**Issue by kozross** [netmail-open/wjelement#41]
Is this intentional? If so, why? It seems like a strange thing to *not* give users the ability to automatically uninstall your library if they wish to.

**Comment by minego** [comment]
This is not implemented by default in cmake. I would gladly accept a pull
request to add it though.

**Comment by penduin** [comment]
This is a good idea and easy to do.  Adding now...

**Comment by penduin** [comment]
...and committed.  I'll look into pkg-config support as well...

**Comment by kozross** [comment]
Everything works great now - thanks very much!

**Comment by penduin** [comment]
Woohoo!  Glad to hear it.  :^)
