### ISSUE TITLE
Direct access to array by index

### ISSUE THREAD

**Issue by robn** [netmail-open/wjelement#44]
I'd like to be able to get an array element by index. I don't see a way to do it. The best I've found is to create a selector from a template eg `sprintf(selector, "[%d]", index)`.

**Comment by robn** [comment]
Further: `sprintf(selector, "{}; prop = '%s'", foo);`.

I wonder if a varargs/formatstr version of the type functions is possible/useful.

**Comment by minego** [comment]
Definitely useful and possible!

The only difficulty really is that the argument order would need to change
so that the selector is at the end. Not hard at all to add.

Perhaps I'll add an F variant of each type function. ie WJEStringF(doc,
action, value, selector format str, ...)

**Comment by robn** [comment]
The F variant is a great idea. It makes it clear what's going on, (theoretically) give slightly higher performance for the non-F versions if you don't need it, and means you don't have to break your API (raw strings are now format strings, potentially dangerous).

**Comment by minego** [comment]
Yeah, that's my thought. I don't dare use the existing values as format
strings. Code should be written with that in mind for it to be safe.

**Comment by penduin** [comment]
WJEGetF and the like have been in for a while now, closing this.  :^)
