### ISSUE TITLE
min/max definitions in xpl.h

### ISSUE THREAD

**Issue by petehug** [netmail-open/wjelement#49]
These definitions can cause a headache in some situations. In some build environments, I need to include standard library files before I (directly or indirectly) include xpl.h. 

I suggest changing these macros to XPL_MIN and XPL_MAX to avoid conflicts.

**Comment by penduin** [comment]
I wonder if we could have those get defined only conditionally, if they're not defined already.  Depending on what and how you're building that still might not be helpful, of course.

Switching to an internal and unlikely-to-clash symbol should be easy enough.  (Either for me or for somebody who wanted to post a patch and/or pull request :^)

**Comment by penduin** [comment]
@HugoKlepsch for the win.  :^)  My apologies if anyone has been waiting on this.
