### ISSUE TITLE
When will release a new version?

### ISSUE THREAD

**Issue by HandyChang** [netmail-open/wjelement#57]
Hey guys:

```
 It is almost one year since version 1.1 release.
 Could you release a new version, thanks.
```

**Comment by minego** [comment]
I've got a few small things I'd like to finish before a new release. I'd
say a week or 2.

**Comment by HandyChang** [comment]
Thanks.

**Comment by penduin** [comment]
Naturally, we're aiming to line up with the next Slackware release.  (I'm completely kidding, but that's coming soon too, and I always make a slackbuild the same time we do a release.  :^)

**Comment by penduin** [comment]
How goes that week or 2, @minego ?  ;^)

@HandyChang : I know he plans to merge our internal wje library and this open one, which have diverged more than we ever intended them to.  I'll keep nagging.

**Comment by pilkch** [comment]
Did the new version get released?  Is there an easy way to find out the release/version history?

**Comment by minego** [comment]
I will try to work on the last needed merges tonight, then we will do a release. Sorry it has been such a delay.

**Comment by minego** [comment]
I've just done the merge so now the internal and open versions are much closer to each other. I'll work with @penduin and we'll make sure an official release gets done.

**Comment by penduin** [comment]
Our apologies that this took so long, vut v1.2 is officially released!  As always let us know if you run into any trouble with it.
