### ISSUE TITLE
Schema case sensitivity inconsistent

### ISSUE THREAD

**Issue by toleressea** [netmail-open/wjelement#60]
The schema logic correctly requires the input property name to match case with the schema property name for validation against the schema object to occur, but the _required_ and _additionalProperties_ json-schema keyword validation is case insensitive. This allows for a situation where an input property name with the incorrect case passes the _required_ validation, but is never matched against the expected schema object. Or in the case of _additionalProperties_, it fails to detect that a property with a differently cased name is included. See below for examples that demonstrate this behavior.

### Case 1: `required`

**schema**: 
```
  { 
    "type": "object", 
    "properties": { "test": { "type": "integer" } }, 
    "required": [ "test" ] 
  }
```
**input1**: `{ "test": "str" }`
**result1**: `FALSE`, test is of incorrect type

**input2**: `{ "TEST": "str" }`
**result2**: `TRUE`

Result1 is correct; result2 is incorrect. The second input passes the _required_ validation, but is not validated against the lowercase "test" property, creating a false positive for the user.

### Case 2: `additionalProperties`

**schema**: 
```
  { 
    "type": "object", 
    "properties": { "test": { "type": "integer" } },
    "additionalProperties": false 
  }
```
**input**: `{ "TEST": "str" }`
**result**: `TRUE`

The result is incorrect. The incorrectly cased property passes the _additionalProperties_ validation, but is not validated against the lowercase "test" schema property, creating a false positive for the user.

**Comment by penduin** [comment]
We might want to fix this somewhere other than in the main selector search functionality, (we had our reasons for wanting case-insensitivity there) but we'll look into this asap.  Good catch!

**Comment by toleressea** [comment]
Fair enough, you know the domain much better than I do! I'll look forward
to seeing what you come up with, thanks!

**Comment by penduin** [comment]
Sorry for the delay!  Micah actually pushed a fix a few days ago which took care of this, among other side effects.  :^)
