### ISSUE TITLE
Schema validation unexpectedly succeeds when key doesn't match patternProperties and additionalProperties=false

### ISSUE THREAD

**Issue by smokris** [netmail-open/wjelement#66]
With this schema…

```
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"patternProperties": {
		"^string[0-9]+$": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
```

and this document…

    {"foo":"bar"}

…since the key doesn't match `patternProperties`, and `additionalProperties` is `false`, I'd expect the document to fail schema validation.  But, with wjelement-1.2, it passes:

    echo 'validate patternProperties-noAdditional.jsonschema' | ./wjecli test.json
    Schema validation: PASS

**Comment by penduin** [comment]
Thanks for the info!  I'll dig into this as soon as I can.  WJE's
regex support uses an optional dependency; do you happen to know if
this behaviour the same with and without it?  (Don't worry about
setting that up, I'm just curious.)

-Owen

**Comment by smokris** [comment]
> do you happen to know if this behaviour the same with and without [regex]?

I'm not sure offhand.  I confirmed that regex support is enabled for my build (I'm successfully using `pattern` in other parts of the schema).

**Comment by penduin** [comment]
Thanks for your patience and I'm sorry it took me so long to get around to this.  I've pushed a fix, please try it out and let me know if I missed anything or broke something else.  :^)  Thanks @smokris !

**Comment by penduin** [comment]
Also, something something Order #66.  Look out Jedi!

**Comment by smokris** [comment]
Excellent.  It's working nicely over here.  Thanks, @penduin!
