### ISSUE TITLE
Error use Raspberry pi 3

### ISSUE THREAD

**Issue by thiagoanselmo** [netmail-open/wjelement#67]
I did the installation, and compiled an example. But at the time of using the error appears.

./json: error while loading shared libraries: libwjelement.so.1: cannot open shared object file: No such file or directory

Help

**Comment by penduin** [comment]
@thiagoanselmo I hope you closed this because you figured it out.  :^)

For the record, what did you end up doing to get things working?  Maybe our build/installation scripts/docs need some touching up, and of course we'd like this to run everywhere with as little irritation as possible.
