### ISSUE TITLE
Exponential memory growth in schema validation

### ISSUE THREAD

**Issue by JayCase** [netmail-open/wjelement#68]
Consider a simple schema like:
{
        "$schema": "http://json-schema.org/draft-03/schema#",
        "type": "array",
        "items": {
                "type": "object",
                "properties": {
                        "headers": {
                                "type": "object",
                                "required": true,
                                "properties": {
                                        "messageId": {
                                                "type": "string",
                                                "required": true
                                        }
                                }
                        },
                        "properties": {
                                "type": "object",
                                "required": false
                        },
                        "body": {
                                "type": "string",
                                "required": true
                        }
                }
        }
}

If the "body" element is ~600 byte string, it takes 12K RAM to validate.
If the "body" element is ~308K byte string, it takes 17.6M RAM to validate.
If the "body" element is ~9.1M byte string, it takes 16.9G (yes, giga bytes) RAM to validate.

**Comment by penduin** [comment]
Yikes!  Clearly we're doing much more than is necessary or wise here.
I'll look into this asap, thanks for catching it!

**Comment by JayCase** [comment]
Attached examples to easily reproduce the issue using validate example.
Digging into this as well, and happy to help in anyway possible, try patches, etc.

[examples.zip](https://github.com/netmail-open/wjelement/files/1012343/examples.zip)

**Comment by penduin** [comment]
How exactly are you measuring how much memory the process takes?  Sounds like you're using the provided "validate.c" example program, is that right?

When I run valgrind's massif heap-monitoring tool:
$ valgrind --tool=massif --time-unit=B ./validate putlarge9.json jsonnew.schema 
...then view it:
$ ms_print massif.out.<pid> |less

I see memory usage grow up to 9.2 meg, just a tad bigger than your "putlarge9.json" file, and stay there.  The validate program dumps both the json and the schema to the console (which i'm guessing your program does not, and shouldn't be too heavy even with a really irresponsible terminal/screen/etc), says it passed, and exits.

Running with your sample files works with no trouble on my workstation, which only has 16gig of actual ram in it (minus a bazillion firefox tabs, a few instances of emacs, gimp, blender, and all the other crap I always have open).  Running through valgrind is a bit slow, naturally, but running by itself is pretty much instant.  I would expect to swap like mad if this were taking up the kinds of ram you're talking about.

Maybe I'm completely missing something, or misunderstanding valgrind (more than possible).  Do you have any more hints on how to duplicate this?

**Comment by penduin** [comment]
Just for fun, I added --stacks=yes to make extra sure all those gigs weren't happening on the stack, and my valgrind report went from 9.202 to 9.203 meg.  So, that's not it either.

I'm trying to imagine what might be substantially different between my Slackware workstation and your AS7/CentOS box, and coming up blank.  I'm using the latest (non-release) WJElement, not that I can think of any recent changes that could have had effects like this.

**Comment by JayCase** [comment]
Well, this is indeed embarrassing.

Turns out there were modifications made to our local repo (back in the Intel days), apparently as some inane attempt to increase performance :(

I've ripped this insanity out, and the universe is a piece again.

So this issue is invalid, a self inflicted wound of days gone by, and *not* a problem with wjelement.

Please except my apologies for the false alarm, and sorry for wasting you time!

**Comment by JayCase** [comment]
Close as invalid.

**Comment by penduin** [comment]
Please don't apologize!  This was good solid community engagement, which is well worth any number of false alarms.  Far from a waste, I consider learning things, working together, and digging into the same software with different goals to be basically an ideal use of my time.

If you are in a sharing mood, I'd be curious to see your changes/optimizations (even the memory-snarfing ones :^) and/or hear what you're using WJE for.  I'm also still curious what you used to determine those RAM sizes, if it wasn't valgrind.

In any case, thank you for the report and for your follow-through.  And of course, never hesitate to open a ticket if you run into other trouble.
