### ISSUE TITLE
Spurious validation errors when using combining keywords

### ISSUE THREAD

**Issue by falstaff84** [netmail-open/wjelement#70]
When validating against a JSON schema with combining keywords, spurious errors might appear. In the pass case this is not a big problem since errors can be simply ignored. However, in case the validation fails, the library user can no longer tell which validation issues are actually relevant.

The attached example leads to this spurious error when using the `validate` example application:

    ...
    schema: good
    (root): required member 'name' not found.
    validation: PASS

[example.zip](https://github.com/netmail-open/wjelement/files/1198951/example.zip)

**Comment by penduin** [comment]
interesting. i'm not sure if i'll have a chance this weekend but i'll dig
into this as soon as i can.

later,
-Owen

**Comment by penduin** [comment]
sorry this is taking so long to get around to!  i have no progress to report but i have not forgotten.  :^)

**Comment by falstaff84** [comment]
Thanks for staying on-top of this issue. It is not urgent from my point of view.

The issue came up while evaluating JSON schema validators. We ended up using Valijson for other reasons (header only, worked well with the JSON parser we use). Btw, I did came across a similar issue in Valijson (https://github.com/tristanpenman/valijson/issues/50).

**Comment by penduin** [comment]
Finally got around to it!  Didn't take long to sort out that our "oneOf" validation should not use the general-purpose error-reporting callback; we want all but one case to fail.  Thank you @falstaff84 for finding this, and for your patience!
