### ISSUE TITLE
Build warnings with -Wparentheses

### ISSUE THREAD

**Issue by jeffreyleifer** [netmail-open/wjelement#76]
wjelement/src/wjelement/schema.c: In function ‘SchemaValidate’:
wjelement/src/wjelement/schema.c:429:3: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
   if(str = WJEString(schema, "[\"$ref\"]", WJE_GET, NULL)) {
   ^
wjelement/src/wjelement/schema.c:652:6: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
      if(sub = WJEObject(schema, "properties", WJE_GET)) {

**Comment by penduin** [comment]
Thanks @jeffreyleifer !  I've fixed this in 4a39d7f..e264361
