### ISSUE TITLE
v4 "required" assertion applied for instance that is not object

### ISSUE THREAD

**Issue by PaulenAndrew** [netmail-open/wjelement#81]
[Section 3.2.1 of JSON Schema Validation specification](
https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-3.2.1) states:

> Most validation assertions only constrain values within a certain
> primitive type. When the type of the instance is not of the type
> targeted by the keyword, the instance is considered to conform to the
> assertion.

If the `required` keyword is used with an array value, per v4 syntax, it is asserted even if the instance being tested is not an object.

For example:
`{"required":["name1"]}` - Schema
`{"name1":null}` - Instance conforms
`{}` - Instance does not conform
`null` - Instance conforms but `WJESchemaValidate()` claims it does not

Below is code for an example console application, expected output and actual output.

```
#include <stdarg.h>
#include "stdafx.h"
#include "wjelement.h"

void ErrCB(void *client, const char *format, ...)
{
	va_list args;
	va_start(args, format);
	vprintf(format, args);
	va_end(args);
	printf("\n");
}

void RunTest(int index, WJElement schema, char* json)
{
	if (WJElement document = WJEParse(json)) {
		printf("Test %d\n", index);
		if (WJESchemaValidate(schema, document, &ErrCB, NULL, NULL, NULL)) {
			printf("OK\n");
		}
		WJECloseDocument(document);
		printf("\n");
	}
}

int main()
{
	XplBool valid;
	if (WJElement schema = WJEParse("{\"required\":[\"name1\"]}")) {
		RunTest(1, schema, "{\"name1\":null}");
		RunTest(2, schema, "{}");
		RunTest(3, schema, "null");
		WJECloseDocument(schema);
	}
	return 0;
}
```

The expected output is as follows:
> Test 1
> OK
> 
> Test 2
> (root): required member 'name1' not found.
> 
> Test 3
> OK

The actual output is as follows:
> Test 1
> OK
> 
> Test 2
> (root): required member 'name1' not found.
> 
> Test 3
> (root): required member 'name1' not found.

**Comment by penduin** [comment]
Very interesting!  I must have completely missed that distinction from the spec years ago.

I will work up a fix ASAP, thank you @PaulenAndrew for spotting this!

**Comment by penduin** [comment]
schema v4+ fix: "required" array ignores non-objects.  thanks @PaulenAndrew !

To github.com:netmail-open/wjelement.git
   07cf03c..d8acb43  master -> master

**Comment by PaulenAndrew** [comment]
Thanks! Yes, it _is_ interesting/weird. You might wonder how I came across it. The example I give to reproduce is simplified, but here's how it applies to the "real World".

I originally discovered it when using [this example "request" JSON](http://integratecapi.com/docs/qgSvcDetailaddressTableCreateFromTemplate.html#qgSvcDetailaddressTableCreateFromTemplate_Example_JSONFile) and [this schema](http://integratecapi.com/docs/qgSvcDetailaddressTableCreateFromTemplate.html#qgSvcDetailaddressTableCreateFromTemplate_RequestSchema).

The "template" property can either be an object or a string, so it uses a "oneOf". The first choice specifies a "type" of "string. The second choice is intended for an object, but specifies "required" without (at the time of writing) specifying "type". WJElement decides that it does not conform to the second choice and so it conforms to one of them, as expected. However, things that validate "correctly", such as https://jsonschemavalidator.net,  decide that it does conform to the second choice and so conforms to both of them, and so does not conform to the overall schema!

**Comment by penduin** [comment]
Thank you for sharing!  It's always fascinating to learn the details of
where WJE winds up.  :^)

Are you getting correct results after the fix?

later,
-Owen

**Comment by PaulenAndrew** [comment]
Yes, it's working for me now, thanks.
