### ISSUE TITLE
(root) is of incorrect type when parsing a string thorugh WJEParse and validating

### ISSUE THREAD

**Issue by fusionJose** [netmail-open/wjelement#82]
I get this error everytime when i try to validate a JSON string with an schema. This JSON string is parsed through WJEParse like in the example _WJEParse("{ 'foo': true, 'bar': 'yup' }", '\'');
Any idea?

**Comment by fusionJose** [comment]
Does it works correctly whth draft 4?

**Comment by penduin** [comment]
this is a bit surprising, i will take a look.  do you have a small schema and document to be validated which fails you could paste here?

**Comment by fusionJose** [comment]
It works correctly. I was validating this json string : "[3, '24556',{'status':'Accepted','currentTime':'2019-07-03T07:25:00.236Z','interval':14400}]". I removed the header ([3, '24556',) and now works correctly.
Thank you very much.
