### ISSUE TITLE
How do I add a header to the JSON frame?

### ISSUE THREAD

**Issue by fusionJose** [netmail-open/wjelement#83]
I want to add something that is not an object,it's a header. I wrote mi code in c with WJEObject and WJEString functions. I made this frame: "{"chargePointVendor":"Upna","chargePointModel":"Grid"}"

But I need to add this: [2, "19389", "{"chargePointVendor":"Upna","chargePointModel":"Grid"}"]

Any idea? Thanks

**Comment by penduin** [comment]
I'm not sure what you mean by "header", but this quick little program will build up the structure you have described:

```
/* gcc -o test -lwjelement test.c */
#include <stdio.h>
#include <wjelement.h>

int main(int argc, char **argv) {
	WJElement obj;
	WJElement arr;

	/* your json object is built, one way or another */
	obj = WJEParse("{\"chargePointVendor\":\"Upna\",\"chargePointModel\":\"Grid\"}");

	/* you want it inside an array, so build a new array */
	arr = WJEArray(NULL, NULL, WJE_NEW);

	/* append your "headers" */
	WJEInt64(arr, "[$]", WJE_NEW, 2);
	WJEString(arr, "[$]", WJE_NEW, "19389");

	/* append the object */
	WJEAttach(arr, obj);

	/* see the resulting structure */
	WJEDump(arr);

	WJECloseDocument(obj);
	return 0;
}
```

**Comment by penduin** [comment]
Hmm, I just noticed the third item in your array is not the object as i thought, but rather a string representation of that object.  Is that what you intended, or does my sample program do what you meant?

**Comment by fusionJose** [comment]
Yes that quick little program does what i want. I will include the header as an array and then append the object.
Thank you very much.
