### ISSUE TITLE
heap-related malloc/free linkage(?) issues

### ISSUE THREAD

**Issue by coreystinson** [netmail-open/wjelement#88]
I ran into an issue with malloc/free between WJElement library and an Visual Studio (MFC/C++) application and the WJEToString() call.

I have compiled WJElement as a static library, 32-bit, debug build, using multi-threaded debug libraries.

Then, I have an Visual Studio MFC (Windows) application linking to that and making WJElement calls, including WJEToString().

In this particular scenario WJEToString() allocates memory but it is the responsibility of the calling application to release it.  With a debug build, I get an heap debugging-related assertion failure on the free() call.  I suspect the reason is that the WJElement library is linked against LIBCRTD.LIB and my application is linked against MSVCRTD.LIB.  I suspect, but don't know for sure.

Calling WJElement's MemFree doesn't solve the issue as this is just a macro that invokes the local version of free().

As a test, I added a WJEMemFree() function as follows to the library itself:

EXPORT void WJEMemFree(void *mem)
{
	if (mem != NULL) MemFree(mem);
}

In this case MemFree() invokes (links) the local version of free from the library's perspective and, sure enough, calling this from my MFC application gets me a version of free() that appears to not trip the assertion.

I hope this is useful in case someone else runs into the same problem.

**Comment by penduin** [comment]
Nice!  That's an interesting case and a good solution.  I'll include it asap.

**Comment by penduin** [comment]
pushed cc087dc..97b8382
thanks @coreystinson !
