### ISSUE TITLE
Possible NULL Pointer Dereference

### ISSUE THREAD

**Issue by saadmunir90** [netmail-open/wjelement#99]
With CPPCheck run, I found out a possible NULL pointer dereference in cli code.

`../wjelement/src/cli/cmds.c
353 | nullPointerRedundantCheck | 476 | warning | Either the condition 'if(selector)' is redundant or there is possible null pointer dereference: selector.
`

On line 353, the `selector` variable might have `NULL` value causing the segmentation fault. In fact, the `selector` is checked at line 334 for `NULL` value. If it is `NULL` there, it would definitely lead to crash at line 353.

**Comment by penduin** [comment]
fixed in 7277535..51cf36d
thanks @saadmunir90 !
